### PR TITLE
Fix path params

### PR DESCRIPTION
**Pull request by IRus**

### CODE REVIEW

**Comment by buy-bitcoin-wth** [comment]
Ай воут фор:
    :+1: [Мерж](http://itx.ai/?pull_request_id=3&repo=Heapy%2Fwth4&amount=5&choice=true&description=Fix+path+params)
    :-1: [Деклайн](http://itx.ai/?pull_request_id=3&repo=Heapy%2Fwth4&amount=5&choice=false&description=Fix+path+params)

**Comment by buy-bitcoin-wth** [comment]
+25. Deposit 25$.

**Comment by buy-bitcoin-wth** [comment]
+25. Deposit 50$.

**Comment by IRus** [comment]
:+1: thx @buy-bitcoin-wth

**Pull request merged**
